[alias]
ci-fmt    = "fmt --all -- --check"
ci-clippy = "clippy --no-default-features --features display-bins-128 --all-targets -- -D warnings"
ci-check  = "check  --no-default-features --features display-bins-128 --all-targets"
ci-test   = "test   --no-default-features --features display-bins-128"