[alias]
ci-fmt    = "fmt --all -- --check"
ci-clippy = "clippy --no-default-features --all-targets -- -D warnings"
ci-check  = "check --no-default-features --all-targets"
ci-test   = "test --no-default-features"